name: Pylint

on:
  push:
    branches: [main, oop]
  pull_request:
    branches: [main, oop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      # Python version 3.10 is not supported yet 
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt
      
      - name: Analyse the Rion Project
        working-directory: ./rion
        run: |
          pylint --rcfile="../.pylintrc" `ls -R|grep .py$|xargs`
      
